# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          João Lucas P Santana
paginate:       5
baseurl:        ""
url:            "https://jlucasps.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         João Lucas P Santana
  url:          http://jlucasps.com
  email:        jlucasps@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/jlucasps/jlucasps.github.io

# Gems
plugins:
  - jekyll-paginate
  - jekyll-sitemap
